// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace MaterialSample
{
	public partial class DescriptionTableViewCell : UITableViewCell
	{
		public DescriptionTableViewCell (IntPtr handle) : base (handle)
		{
		}
	}
}
