top_srcdir=../..
TOP=$(top_srcdir)

include $(top_srcdir)/commands.make

BUILDLIST=Screenshooter
SAMPLESDIR=samples/ScreenshooterSample
NUGETLIST=nuget/Screenshooter.nuspec

include $(top_srcdir)/basic-component.make
