// This file has been autogenerated from parsing an Objective-C header file added in Xcode.
using System;
using System.Drawing;
using Xamarin.Themes;
using TrackBeamTheme_Sample_iOS.Model;
using Xamarin.Themes.Core;
using Foundation;
using UIKit;

namespace TrackBeamTheme_Sample_iOS.Views.iPhone {
	public partial class DetailThemeController : UIViewController {
		Track track;

		public DetailThemeController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad ()
		{
			var edit = new UIBarButtonItem (UIBarButtonSystemItem.Add);
			NavigationItem.SetRightBarButtonItem (edit, false);

			base.ViewDidLoad ();
		}

		public override void ViewWillAppear (bool animated)
		{
			base.ViewWillAppear (animated);

			ThemeManager.Current.Apply(View);

			this.Title = track.Name;

			artistLabel.Text = track.Artist;
			trackLabel.Text = track.Name;
			albumImageView.Image = track.LargeImage;
		}

		internal void SetTrack (Track trackToDetail)
		{
			if (trackToDetail == null)
				throw new ArgumentNullException ("trackToDetail");
			track = trackToDetail;
		}
			
	}
}
