// This file has been autogenerated from parsing an Objective-C header file added in Xcode.using System;
using System;
using System.Drawing;
using Xamarin.Themes;
using Xamarin.Themes.Core;
using Xamarin.Themes.TrackBeam;
using Foundation;
using UIKit;

namespace TrackBeamTheme_Sample_iOS.Views.iPhone {
	public partial class ElementThemeController : UIViewController {


		public ElementThemeController (IntPtr handle) : base (handle)
		{
		}
			

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();

			this.Title = "Elements";

			//setup the theme
			ThemeManager.Current.Apply(View)
				.Apply(loginButton)
				.Apply(registerButton)
				.Apply(textField);

			//set up the switches
			onSwitch.IsOn = true;
			offSwitch.IsOn = false;

			//
			var itemBtn = new UIBarButtonItem ("Close", UIBarButtonItemStyle.Plain, null);
			itemBtn.Clicked += (object sender, EventArgs e) => 
			{
				this.DismissViewController(true, null);
			};
			NavigationItem.SetRightBarButtonItem (itemBtn, false);

			//
			textField.ShouldReturn = TextFieldShouldReturn;
			sliderView.ValueChanged += (object sender, EventArgs e) => 
			{
				progressView.Progress = sliderView.Value;
			};
		}

			
		bool TextFieldShouldReturn (UITextField aTextField)
		{
			aTextField.ResignFirstResponder ();
			return true;
		}
			
	}
}
