parameters:
  dependsOn: 'build'
  signTags: 'true'
  forceSignVariable: 'CodeSign'
  additionalConditions: 'false'
  signingTemplate: 'sign-artifacts.yml@xamarin-templates'

jobs:
  - ${{ if eq(variables['System.TeamProject'], 'devdiv') }}:
    - job: signing
      displayName: 'Sign NuGets'
      variables:
        skipComponentGovernanceDetection: true
      dependsOn:
        - ${{ parameters.dependsOn }}
      pool:
        name: VSEng-XamarinCustom
        demands:
          - corpnet
      condition: and(
        succeeded(),
        or(
          and(
            eq('${{ parameters.signTags }}', 'true'),
            startsWith(variables['Build.SourceBranch'], 'refs/tags/')
          ),
          and(
            ne('${{ parameters.forceSignVariable }}', ''),
            eq(variables['${{ parameters.forceSignVariable }}'], 'true')
          ),
          eq('${{ parameters.additionalConditions }}', 'true')
        ))
      steps:
        - checkout: none
        - template: $[ parameters.signingTemplate ]
          parameters:
            targetFolder: '$(Build.ArtifactStagingDirectory)/signed'
        - task: PublishBuildArtifacts@1
          displayName: 'Publish the nuget-signed artifacts'
          inputs:
            artifactName: nuget-signed
            pathToPublish: '$(Build.ArtifactStagingDirectory)/signed'
