parameters:
  dependsOn: 'build'
  signTags: 'true'
  forceSignVariable: 'CodeSign'
  additionalConditions: 'false'
  signingStep: [ ]

jobs:
  - ${{ if eq(variables['System.TeamProject'], 'devdiv') }}:
    - job: signing
      displayName: 'Sign NuGets'
      variables:
        skipComponentGovernanceDetection: true
      dependsOn:
        - ${{ parameters.dependsOn }}
      pool:
        name: VSEng-XamarinCustom
        demands:
          - corpnet
      condition: and(
        succeeded(),
        or(
          and(
            eq('${{ parameters.signTags }}', 'true'),
            startsWith(variables['Build.SourceBranch'], 'refs/tags/')
          ),
          and(
            ne('${{ parameters.forceSignVariable }}', ''),
            eq(variables['${{ parameters.forceSignVariable }}'], 'true')
          ),
          eq('${{ parameters.additionalConditions }}', 'true')
        ))
      steps:
        - checkout: none
        - ${{ each step in parameters.signingStep }}:
          - ${{ each pair in step }}:
              ${{ if ne(pair.key, 'parameters') }}:
                ${{ pair.key }}: ${{ pair.value }}
            parameters:
              targetFolder: '$(Build.ArtifactStagingDirectory)/signed'
              ${{ if job.parameters }}:
              - ${{ job.parameters }}
        - task: PublishBuildArtifacts@1
          displayName: 'Publish the nuget-signed artifacts'
          inputs:
            artifactName: nuget-signed
            pathToPublish: '$(Build.ArtifactStagingDirectory)/signed'
