parameters:
  signTags: true
  forceSignVariable: 'CodeSign'
  signBranches: [ 'refs/heads/master' ]

jobs:
  - job: test
    pool:
      name: Hosted Ubuntu 1604
    condition: and(
      succeeded(),
      or(
        and(
          eq('${{ parameters.signTags }}', True),
          startsWith(variables['Build.SourceBranch'], 'refs/tags/')
        ),
        containsValue(${{ parameters.signBranches }}, variables['Build.SourceBranch']),
        and(
          ne('${{ parameters.forceSignVariable }}', ''),
          eq(variables['${{ parameters.forceSignVariable }}'], True)
        )
      ))
    steps:
      - checkout: none

    # condition: and(
    #   succeeded(),
    #   or(
    #     and(
    #       eq('${{ parameters.signTags }}', 'true'),
    #       startsWith(variables['Build.SourceBranch'], 'refs/tags/')
    #     ),
    #     and(
    #       ne('${{ parameters.signBranches }}', ''),
    #       in(variables['Build.SourceBranch'], ${{ parameters.signBranches }})
    #     ),
    #     and(
    #       ne('${{ parameters.forceSignVariable }}', ''),
    #       eq(variables['${{ parameters.forceSignVariable }}'], 'true')
    #     )
    #   ))

#          containsValue(${{ parameters.signBranches }}, variables['Build.SourceBranch'])