using System;
using System.Xml.Serialization;

namespace Xamarin.iOS.Binding.Transformer
{
    [XmlRoot(ElementName = "model")]
    public class ApiTypeModel
    {
        [XmlAttribute(AttributeName = "autogeneratedname")]
        public bool AutoGeneratedName { get; set; }

        public ApiTypeModel()
        {

        }
    }
}
