// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace SDWebImageSampleMac
{
	public partial class MainWindowController : NSWindowController
	{
		public ViewController CollectionViewController
		{
			get { return ContentViewController as ViewController; }
		}

		public MainWindowController (IntPtr handle) : base (handle)
		{
            
		}

        public override void WindowDidLoad()
        {
            
        }
	}
}
